//SPDX-License-Identifier: LGPL-3.0-only 
/*
Copyright(C) 2025 SINTEF
This file is part of the Scoop Utilities project.
*/

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Sintef.Scoop.Utilities
{
	/// <summary>
	/// Parses the result of a <see cref="GeneralLogger"/>.
	/// </summary>
	public class GeneralLoggerParser
	{
		/// <summary>
		/// A log entry
		/// </summary>
		public class LogEntry
		{			
			/// <summary>
			/// Timestamp of the log entry
			/// </summary>
			public DateTime Timestamp { get; private set; }

			/// <summary>
			/// properties of log entry
			/// </summary>
			public IReadOnlyDictionary<string, IReadOnlyCollection<string>> Properties { get; private set; }

			/// <summary>
			/// log message
			/// </summary>
			public string Message { get; private set; }

			/// <summary>
			/// construction
			/// </summary>
			public LogEntry(DateTime timestamp, IReadOnlyDictionary<string, IReadOnlyCollection<string>> properties, string msg)
			{
				Timestamp = timestamp;
				Properties = properties;
				Message = msg;
			}
		}

		/// <summary>
		/// Parses the file representing a log generated by a <see cref="GeneralLogger"/>
		/// </summary>
		/// <param name="filename">The file to parse</param>
		/// <returns>The list of entries in the order as they occur in the log</returns>
		static public List<LogEntry> Parse(string filename)
		{
			using (var stream = new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.Read))
			{
				return Parse(stream);
			}
		}

		/// <summary>
		/// Parses the stream representing a log generated by a <see cref="GeneralLogger"/>
		/// </summary>
		/// <param name="stream">The stream to parse</param>
		/// <returns>The list of entries in the order as they occur in the log</returns>
		static public List<LogEntry> Parse(Stream stream)
		{
			// ++++++++++++++++++++++++++++++++++
			// setup for string manipulation
			// ++++++++++++++++++++++++++++++++++

			IEnumerable<StringPairManipulation.Pair> noOpPairs = StringPairManipulation.DefineStartEndPairs(new char[] { '"', '\'' });

			StringPairManipulation.Pair propertyPair = new StringPairManipulation.Pair('[', ']');
			StringPairManipulation.Pair messagePair = new StringPairManipulation.Pair(new StringPairManipulation.ExtendedChar(':'),
					new StringPairManipulation.ExtendedChar(StringPairManipulation.ExtendedChar.CharacterTypes.EndOfString));
			StringPairManipulation.Pair propertyNameValuePair = new StringPairManipulation.Pair(new StringPairManipulation.ExtendedChar('='),
								new StringPairManipulation.ExtendedChar(StringPairManipulation.ExtendedChar.CharacterTypes.EndOfString));

			List<StringPairManipulation.Pair> lineDelimeter = new List<StringPairManipulation.Pair>();
			lineDelimeter.Add(propertyPair);
			lineDelimeter.Add(messagePair);
			List<StringPairManipulation.Pair> propertyDelimeter = new List<StringPairManipulation.Pair>();
			propertyDelimeter.Add(propertyNameValuePair);

			StringPairManipulation.SplitOptions splitOptions = new StringPairManipulation.SplitOptions();
			splitOptions.IncludeDelimeters = false;
			splitOptions.NestedInsideDefinition = StringPairManipulation.SplitOptions.NestedInsideDefinitions.Total;
			splitOptions.EnableNestingInDelimeterPairs = false;
			splitOptions.EnableDelimeterNestingInNonSplitPairs = false;
			splitOptions.EnableNonSplitNestingInNonSplitPairs = false;

			StringPairManipulation.ManipulateOptions manipulateOptions =
				new StringPairManipulation.ManipulateOptions() { EnableNoOpNesting = false };

			List<char> escapeChars = (new char[] { '[', ']', '=' }).ToList<char>();

			// ++++++++++++++++++++++++++++++++++
			// start parsing
			// ++++++++++++++++++++++++++++++++++
			List<LogEntry> entries = new List<LogEntry>();

			StreamReader reader = new StreamReader(stream);
			string line = null;
			long lineCounter = 0;
			while ((line = reader.ReadLine()) != null)
			{
				++lineCounter;

				// ------------------------
				// extract timestamp
				// ------------------------

				DateTime timestamp = DateTime.MinValue;

				int length = line.Length;
				while(true)
				{
					// explicitly disallow trailing whitespace and trailing ':' in timestamp (some cultures accept this in timestamp parsing)
					while (length > 0 && (line[length - 1] == ':' || Char.IsWhiteSpace(line, length-1)))
						--length;

					if (length == 0)
						break;

					if (DateTime.TryParse(line.Substring(0, length), out timestamp))
						break;

					--length;
				}

				// did we find a timestamp?
				if (timestamp == DateTime.MinValue)
				{
					LogWarning("timestamp invalid, ignoring line", lineCounter);
					continue;
				}

				line = line.Substring(length);

				// ------------------------
				// split remaining line
				// ------------------------
				StringPairManipulation.IReadOnlyStringPairSplitResult splitResult =
					StringPairManipulation.Split(line, lineDelimeter, noOpPairs, splitOptions);

				// ------------------------
				// extract properties from split
				// ------------------------
				Dictionary<string, HashSet<string>> properties = new Dictionary<string, HashSet<string>>();
				foreach (StringPairManipulation.SingleStringPairSplitString element in splitResult.EntriesForDelimeter(propertyPair))
				{
					var result = StringPairManipulation.Split(element.String, propertyDelimeter, noOpPairs, splitOptions);
					string propertyName = result.Count > 0 ? result[0].String.Trim() : null;
					string propertyValue = result.Count > 1 ? result[1].String.Trim() : null;
					if (propertyName == null || propertyName.Length == 0)
					{
						LogWarning("Ignoring property with empty property name", lineCounter);
						continue;
					}
					if (propertyValue != null && propertyValue.Length == 0)
						propertyValue = null;

					propertyName = StringPairManipulation.Unescape(propertyName, escapeChars, noOpPairs, manipulateOptions);
					if (propertyValue != null)
						propertyValue = StringPairManipulation.Unescape(propertyValue, escapeChars, noOpPairs, manipulateOptions);

					if (!properties.ContainsKey(propertyName))
						properties[propertyName] = new HashSet<string>();
					properties[propertyName].Add(propertyValue);
				}

				// ------------------------
				// extract message from split
				// ------------------------
				var messageResults = splitResult.EntriesForDelimeter(messagePair);
				string msg = messageResults.Count > 0 ? messageResults[0].String.Trim() : null;

				// Missing message : after last property?
				if (msg == null && splitResult.Last().DefiningPair == null)
				{
					if (splitResult.Last().String.Trim().Length > 0)
					{
						LogWarning("No ':' starting message found, taking all text after last property"+
							" / timestamp if no property as message", lineCounter);
						msg = splitResult.Last().String.Trim();
					}
				}

				// ------------------------
				// check for extra warnings to write
				// ------------------------
				foreach (var ignored in splitResult.EntriesForDelimeter(null))
				{
					if (ignored == splitResult.Last())
						continue;

					if (ignored.String.Trim().Length > 0)
					{
						LogWarning("Text between properties and/or between last property and \":\" ignored", lineCounter);
						break;
					}
				}

				// ------------------------
				// add entry
				// ------------------------
				Dictionary<string, IReadOnlyCollection<string>> copy = new Dictionary<string, IReadOnlyCollection<string>>();
				foreach (string key in properties.Keys)
					copy[key] = properties[key] as IReadOnlyCollection<string>;
				entries.Add(new LogEntry(timestamp, copy, msg));
			}

			return entries;
		}

		static private void LogWarning(string msg, long line)
		{
			string output = "WARNING! ";
			output += "Line " + line + ": " + msg;
			Console.Out.WriteLine(output);
		}
	}
}
