//SPDX-License-Identifier: LGPL-3.0-only 
/*
Copyright(C) 2025 SINTEF
This file is part of the Scoop Utilities project.
*/

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Sintef.Scoop.Utilities
{
	/// <summary>
	/// A parser for parsing multidimensional numpy arrays from python into C# multidimensional arrays or arrays of arrays. Currently only tables of basic
	/// numeric types likes integers or floats in various sizes are supported, arrays of objects or strings are not supported.
	///
	/// This parses the table into arrays of arrays, so that it is possible to parse multidimensional tables that are larger than what a single multidimensional
	/// array in C# can support. Each dimension is limited to the number of elements to what C# can handle however, i.e. at most Int.MaxValue elements in a
	/// single dimension.
	/// </summary>
	public class NpyParser : IDisposable
	{
		/// <summary>
		/// The type of each element in the array.
		/// </summary>
		public Type DataType { get; }

		/// <summary>
		/// The size of <see cref="DataType"/> in bytes.
		/// </summary>
		public int DataSize { get; }

		/// <summary>
		/// The shape of the table.
		/// </summary>
		public ulong[] Shape => _shape.ToArray();

		/// <summary>
		/// True if the values are stored in little endian order in the file, false if big endian. If null this means that byte order is not applicable, for
		/// instance if the data type is a byte.
		/// </summary>
		public bool? IsLittleEndian { get; private set; }

		/// <summary>
		/// True if the table in the file is stored in opposite endianness than used by the system. If so parsing will be a bit more costly.
		/// </summary>
		public bool HasOppositeEndianness => IsLittleEndian.HasValue && _systemIsLittleEndian != IsLittleEndian;

		/// <summary>
		/// True if the data is stored in Fortran order instead of C order in the file. Parsing tables stored in Fortran order will have a significant performance
		/// penalty.
		/// </summary>
		public bool HasFortranOrder { get; }

		/// <summary>
		/// Returns an array with the values from the parsed table. If the table is multi dimensional, the result will be arrays of arrays with sufficient
		/// dimensionality.
		/// 
		/// There is a small performance penalty for parsing files with opposite endianness of the system. There is a larger penalty for parsing tables which are
		/// stored in fortran order.
		///
		/// This method may not be invoked multiple times on same parser object to create multiple arrays. Trying to parse again will result in an exception.
		/// </summary>
		/// <typeparam name="T">The type parameter expected from the array, for instance if you have a three dimensional table of 32bit integers then the expected
		/// type is int[][][].</typeparam>
		/// <returns>Typed array or null if incompatible type is specified.</returns>
		public T ParseTable<T>() where T : class
		{
			if (_stream is null)
			{
				throw new InvalidOperationException("Can't parse the table after the parser has been closed!");
			}

			if (Shape.Any(x => x > int.MaxValue))
			{
				throw new InvalidOperationException("Table has an dimension with too many elements to be fit into a .NET array");
			}

			int depth = 0;
			var type = typeof(T);
			while (type is { IsArray: true })
			{
				type = type.GetElementType();
				depth++;
			}

			if (depth != Shape.Length)
			{
				throw new ArgumentException("The given type does not have the correct number of dimensions to store the table");
			}

			if (type != DataType)
			{
				throw new ArgumentException($"The given element type ({type}) does not match the contents of parsed table ({DataType})");
			}

			var array = CreateArray(0).Single();

			if (!HasFortranOrder)
			{
				ParseCOrderedData(array);
			}
			else
			{
				ParseFOrderedData(array);
			}

			return array as T;
		}

		/// <summary>
		/// Opens the given .npy file and parses the header so the client can determine dimensions and data type of the table. The file must be a valid file
		/// generated by numpy.save or compatible software.
		/// </summary>
		/// <param name="fileName">The file to parse.</param>
		/// <returns>Returns a parser object which can be used to inspect the contents and parse it into C# arrays.</returns>
		public static NpyParser OpenNpyFile(string fileName)
		{
			FileStream stream = new(fileName, FileMode.Open, FileAccess.Read, FileShare.Read);
			return OpenNpyFile(stream);
		}
		
		/// <summary>
		/// Parses the given stream which is expected to be of a valid .npy file. The header is parsed so the client can determine dimensions and data type of the
		/// table. 
		/// </summary>
		/// <param name="stream">The file to parse.</param>
		/// <returns>Returns a parser object which can be used to inspect the contents and parse it into C# arrays.</returns>
		public static NpyParser OpenNpyFile(Stream stream)
		{
			BinaryReader reader = new(stream, new ASCIIEncoding());

			if (reader.ReadByte() != 0x93 ||
			    reader.ReadByte() != 0x4e ||
			    reader.ReadByte() != 0x55 ||
			    reader.ReadByte() != 0x4d ||
			    reader.ReadByte() != 0x50 ||
			    reader.ReadByte() != 0x59)
			{
				throw new ArgumentException("Given file is not a valid numpy file");
			}

			var majorVersion = reader.ReadByte();
			var minorVersion = reader.ReadByte();

			if (minorVersion != 0)
			{
				throw new ArgumentException($"Parser does not support files with minor version {minorVersion}");
			}

			int headerSize;
			if (majorVersion == 1)
			{
				headerSize = reader.ReadInt16();
			}
			else if (majorVersion == 2 || majorVersion == 3)
			{
				headerSize = reader.ReadInt32();
			}
			else
			{
				throw new ArgumentException($"Parser does not support files with major version {majorVersion}");
			}

			var headerBytes = reader.ReadBytes(headerSize);

			string header;

			if (majorVersion == 3)
			{
				// Header is encoded in utf-8 in this version
				var encoding = new UTF8Encoding();
				header = new string(encoding.GetChars(headerBytes));
			}
			else
			{
				// Header is ascii in the first two versions
				var encoding = new ASCIIEncoding();
				header = new string(encoding.GetChars(headerBytes));
			}

			var headerFormatException = new ArgumentException("Header in given file appear broken");
			var strip = ExtractSubstringBetween(header, '{', '}');
			var kvps = SplitKeyValuePairs(strip);

			var kvTrimChars = new[] { ' ', '\'' };
			string description = null, fortranOrderString = null, shapeString = null;
			foreach (var kvp in kvps)
			{
				var keyAndValue = kvp.Split(':');
				if (keyAndValue.Length == 0)
				{
					continue;
				}

				if (keyAndValue.Length != 2)
				{
					throw headerFormatException;
				}

				var key = keyAndValue.First().Trim(kvTrimChars);
				var value = keyAndValue.Last().Trim(kvTrimChars);
				switch (key)
				{
					case "descr":
						description = value;
						break;
					case "fortran_order":
						fortranOrderString = value;
						break;
					case "shape":
						shapeString = value;
						break;
					default:
						throw headerFormatException;
				}
			}

			if (description == null || fortranOrderString == null || shapeString == null)
			{
				throw headerFormatException;
			}

			var type = GetType(description.Trim(), out var dataSize, out var isLittleEndian);
			bool fortranOrder = fortranOrderString.Trim().ToLower() switch
			{
				"false" => false,
				"true" => true,
				_ => throw headerFormatException
			};
			var shape = ExtractSubstringBetween(shapeString, '(', ')').Split(',').Where(x => x.Trim().Length != 0).Select(ulong.Parse).ToArray();
			ulong totalSize = dataSize;
			foreach (var t in shape)
			{
				totalSize = checked(totalSize * t);
			}

			return new NpyParser(stream, reader, shape, fortranOrder, isLittleEndian, type, (int)dataSize);
		}

		/// <summary>
		/// Immediately closes the file containing the table. The data can no longer be parsed without opening the file again.
		/// </summary>
		public void Close()
		{
			Dispose();
		}

		/// <summary>
		/// Disposes the parser, freeing up resources held by the class.
		/// </summary>
		public void Dispose()
		{
			_reader?.Dispose();
			_reader = null;

			_stream?.Dispose();
			_stream = null;
		}

		/// <summary>
		/// Splits the header dictionary into strings for each kvp pair which are separated by comma chars. Comma chars inside parenthesis will be included
		/// in keys and values. 
		/// </summary>
		/// <param name="str">The header string</param>
		/// <returns>A string for each kvp in the dictionary</returns>
		internal static IEnumerable<string> SplitKeyValuePairs(string str)
		{
			int parenthesisLevel = 0;
			var remaining = str.Trim();

			while (remaining.Length > 0)
			{
				for (int i = 0; i < remaining.Length; ++i)
				{
					var c = remaining[i];
					if (c == '(')
					{
						parenthesisLevel++;
					}
					else if (c == ')')
					{
						parenthesisLevel--;
					}
					else if (c == ',')
					{
						if (parenthesisLevel == 0)
						{
							var substring = remaining.Substring(0, i).Trim();
							if (substring.Length > 0)
							{
								yield return substring;
							}

							remaining = remaining.Substring(i + 1).Trim();
							break;
						}
					}
					else if (i == remaining.Length - 1)
					{
						if (parenthesisLevel != 0)
						{
							throw new FormatException("Not terminated parenthesis in header");
						}

						yield return remaining.Trim();
						yield break;
					}
				}
			}
		}

		/// <summary>
		/// Figues out the data type based on the dtype string in the header, and also the size and endianness.
		/// </summary>
		/// <param name="dtype">The string describing the data type.</param>
		/// <param name="bytes">The number of bytes in an element of the data type.</param>
		/// <param name="isLittleEndian">True if the element is stored as little endian, false if it is big endian or null if it is irrelevant.</param>
		/// <returns>The c# type corresponding to the given data type.</returns>
		/// <exception cref="NotSupportedException">This implementation does not support the given type.</exception>
		private static Type GetType(string dtype, out uint bytes, out bool? isLittleEndian)
		{
			isLittleEndian = GetIsLittleEndian(dtype);
			bytes = UInt32.Parse(dtype.Substring(2));

			string typeCode = dtype.Substring(1);

			switch (typeCode)
			{
				case "b1":
					return typeof(bool);
				case "i1":
					return typeof(Byte);
				case "i2":
					return typeof(Int16);
				case "i4":
					return typeof(Int32);
				case "i8":
					return typeof(Int64);
				case "u1":
					return typeof(Byte);
				case "u2":
					return typeof(UInt16);
				case "u4":
					return typeof(UInt32);
				case "u8":
					return typeof(UInt64);
				case "f4":
					return typeof(Single);
				case "f8":
					return typeof(Double);
				default:
				{
					throw new NotSupportedException("Not supported type");
				}
			}
		}

		/// <summary>
		/// Returns true if the given type is little endian, false if it is big endian or null if endianness is irrelevant for the type.
		/// </summary>
		/// <exception cref="NotSupportedException"></exception>
		private static bool? GetIsLittleEndian(string type)
		{
			bool? littleEndian;

			switch (type[0])
			{
				case '<':
					littleEndian = true;
					break;
				case '>':
					littleEndian = false;
					break;
				case '|':
					littleEndian = null;
					break;
				default:
					throw new NotSupportedException("Not supported endianness");
			}

			return littleEndian;
		}

		/// <summary>
		/// Extracts the part of the string between the given first and last char. Both chars must be present in the string once each and the last char can not
		/// come before the first, or exception will be thrown.
		/// </summary>
		/// <param name="original">The string to extract from.</param>
		/// <param name="first">The char appearing before the extracted string</param>
		/// <param name="last">The first char appearing after the extracted string</param>
		private static string ExtractSubstringBetween(string original, char first, char last)
		{
			var firstIndex = original.IndexOf(first);
			var lastFirstIndex = original.LastIndexOf(first);
			var lastIndex = original.IndexOf(last);
			var lastLastIndex = original.LastIndexOf(last);
			if (firstIndex < 0 || lastIndex < 0 || firstIndex != lastFirstIndex || lastIndex != lastLastIndex)
			{
				throw new FormatException("Unexpected format");
			}

			return original.Substring(firstIndex + 1, lastIndex - firstIndex - 1);
		}

		/// <summary>
		/// Gets an innermost array, a.k.a the array which has an element type equal to the <see cref="DataType"/>, at the given multi dimensional index.
		/// </summary>
		/// <param name="index">The index of the innermost array, i.e. all but the last index is used to identify the array.</param>
		/// <param name="array">The full multi dimensional jagged array.</param>
		/// <returns>The desired array.</returns>
		/// <exception cref="InvalidOperationException"></exception>
		private Array GetInnermostArray(ulong[] index, Array array)
		{
			Array innermost = array;
			for (int i = 0; i < index.Length - 1; ++i)
			{
				innermost = innermost.GetValue((int)index[i]) as Array;
				if (innermost == null)
				{
					throw new InvalidOperationException("Array does not have sufficient depth for the given index");
				}
			}

			return innermost;
		}

		/// <summary>
		/// Reads in table in C order.
		/// </summary>
		/// <param name="array">The array which will be populated</param>
		private void ParseCOrderedData(Array array)
		{
			var bufferSize = (int)Shape.Last() * DataSize;
			var buffer = new byte[bufferSize];
			var index = new ulong[Shape.Length];

			foreach (var currIndex in COrderedIndices(0, Shape.Length - 1, index))
			{
				var subarray = GetInnermostArray(currIndex, array);
				int read = _reader.Read(buffer, 0, bufferSize);
				if (read < bufferSize)
				{
					throw new InvalidOperationException("Stream does not contain enough data");
				}

				ReverseIfOppositeEndianness(buffer);
				Buffer.BlockCopy(buffer, 0, subarray, 0, buffer.Length);
			}
		}

		/// <summary>
		/// Reads in table in Fortran order.
		/// </summary>
		/// <param name="array">The array which will be populated</param>
		private void ParseFOrderedData(Array array)
		{
			var bufferSize = DataSize;
			var buffer = new byte[bufferSize];
			var index = new ulong[Shape.Length];

			foreach (var currIndex in FortranOrderedIndices(Shape.Length - 1, index))
			{
				var subarray = GetInnermostArray(currIndex, array);
				int read = _reader.Read(buffer, 0, bufferSize);
				if (read < bufferSize)
				{
					throw new InvalidOperationException("Stream does not contain enough data");
				}

				ReverseIfOppositeEndianness(buffer);

				Buffer.BlockCopy(buffer, 0, subarray, (int)currIndex.Last() * DataSize, buffer.Length);
			}
		}

		/// <summary>
		/// Converts the data in the given buffer from little to big endian or vice versa if the file has the opposite endianness of the system.
		/// </summary>
		/// <param name="buffer">A byte buffer containing the data to be converted.</param>
		private void ReverseIfOppositeEndianness(byte[] buffer)
		{
			if (HasOppositeEndianness)
			{
				for (int i = 0; i < buffer.Length; i += DataSize)
				{
					Array.Reverse(buffer, i, DataSize);
				}
			}
		}

		/// <summary>
		/// Enumerates the table indices in the order the data appears in the data file. This assumes the table is stored in "C" order. The indices are enumerated
		/// partially up to the given max depth, the remaining sub indices will remain 0.
		/// </summary>
		/// <param name="depth">The current recursion depth, for c order this should start at the first dimension.</param>
		/// <param name="maxDepth">The max reducrsion depth (or last dimension) to enumerate to .</param>
		/// <param name="index">The multi dimensional index.</param>
		/// <returns>The indices in C order.</returns>
		private IEnumerable<ulong[]> COrderedIndices(int depth, int maxDepth, ulong[] index)
		{
			if (depth == maxDepth)
			{
				yield return index;
			}
			else
			{
				int numElementsInDimension = (int)Shape[depth];
				for (int i = 0; i < numElementsInDimension; ++i)
				{
					index[depth] = (ulong)i;
					foreach (var subIndex in COrderedIndices(depth + 1, maxDepth, index))
					{
						yield return subIndex;
					}

					index[depth] = 0UL;
				}
			}
		}

		/// <summary>
		/// Enumerates the table indices in the order the data appears in the data file. This assumes the table is stored in "Fortran" order.
		/// </summary>
		/// <param name="depth">The current recursion depth, for fortran order this should start at the last dimension.</param>
		/// <param name="index">The multi dimensional index.</param>
		/// <returns>The indices in fortran order.</returns>
		private IEnumerable<ulong[]> FortranOrderedIndices(int depth, ulong[] index)
		{
			if (depth == -1)
			{
				yield return index;
			}
			else
			{
				int numElementsInDimension = (int)Shape[depth];
				for (int i = 0; i < numElementsInDimension; ++i)
				{
					index[depth] = (ulong)i;
					foreach (var subIndex in FortranOrderedIndices(depth - 1, index))
					{
						yield return subIndex;
					}

					index[depth] = 0UL;
				}
			}
		}

		/// <summary>
		/// Creates arrays of arrays recursively to construct a full jagged array with the desired shape.
		/// </summary>
		/// <param name="depth">The current array depth</param>
		/// <returns>The populated arrays at the given depth.</returns>
		private IEnumerable<Array> CreateArray(int depth)
		{
			if (depth == Shape.Length - 1)
			{
				int len = depth > 0 ? (int)Shape[depth - 1] : 1;
				for (int i = 0; i < len; ++i)
				{
					Array array = Array.CreateInstance(DataType, (int)Shape[depth]);
					yield return array;
				}
			}
			else
			{
				int len = depth > 0 ? (int)Shape[depth - 1] : 1;

				for (int i = 0; i < len; ++i)
				{
					Array newArr = null;
					bool first = true;
					int j = 0;
					foreach (var value in CreateArray(depth + 1))
					{
						if (first)
						{
							newArr = Array.CreateInstance(value.GetType(), (int)Shape[depth]);
						}

						newArr.SetValue(value, j++);
						first = false;
					}

					yield return newArr;
				}
			}
		}

		/// <summary>
		/// A stream to read the data from.
		/// </summary>
		private Stream _stream;

		/// <summary>
		/// A reader used to read the file data.
		/// </summary>
		private BinaryReader _reader;

		/// <summary>
		/// Set to true if the system the code is running on is little endian.
		/// </summary>
		private readonly bool _systemIsLittleEndian;

		/// <summary>
		/// Backing field for the shape.
		/// </summary>
		private readonly ulong[] _shape;

		/// <summary>
		/// Constructs a parser object.
		/// </summary>
		/// <param name="stream">The stream from which the file is parsed</param>
		/// <param name="reader">A reader used to parse the file. The stream and reader must be positioned at the start of the values in the array.</param>
		/// <param name="shape">The shape of the data table.</param>
		/// <param name="hasFortranOrder">True if table stored in fortran order, false if in c order.</param>
		/// <param name="isLittleEndian">True if elements are stored in little endian order, false if big endian or null if irrelevant.</param>
		/// <param name="dataType">The c# type of the data elements.</param>
		/// <param name="dataSize">The size odf the data elements in bytes.</param>
		private NpyParser(Stream stream, BinaryReader reader, ulong[] shape, bool hasFortranOrder, bool? isLittleEndian, Type dataType, int dataSize)
		{
			_stream = stream;
			_reader = reader;
			_systemIsLittleEndian = BitConverter.IsLittleEndian;
			_shape = shape;
			HasFortranOrder = hasFortranOrder;
			IsLittleEndian = isLittleEndian;
			DataType = dataType;
			DataSize = dataSize;
		}
	}
}