//SPDX-License-Identifier: LGPL-3.0-only 
/*
Copyright(C) 2025 SINTEF
This file is part of the Scoop Utilities project.
*/

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;

namespace Sintef.Scoop.Utilities.GUI
{
	/// <summary>
	/// An assignment of colors to a collection of objects.
	/// Colors may be specified manually or generated automatically.
	/// </summary>
	public class ColorPalette
	{
		/// <summary>
		/// The maximum number of distinct colors generated by the palette.
		/// If there are more objects than this, some of them will share the same color.
		/// </summary>
		public int MaxColors { get; set; } = 100;

		/// <summary>
		/// The color assigned to each object
		/// </summary>
		private Dictionary<object, Color> _colors = new Dictionary<object,Color>();

		/// <summary>
		/// The random number generator to use
		/// </summary>
		private Random _rand = new Random();

		/// <summary>
		/// Assigns the given color to the given object.
		/// The object can be null, in which case the color will just be avoided
		/// when creating new colors.
		/// </summary>
		/// <param name="color">The color to assign</param>
		/// <param name="owner">The object to assign to color to</param>
		public void AssignColor(Color color, object owner = null)
		{
			owner = owner ?? new object();

			_colors[owner] = color;
		}

		/// <summary>
		/// Returns the color assigned to the given object. If a color has not already been
		/// assigned, assigns a new color that is generated by trying to make it as different from 
		/// the other assigned colors as possible.
		/// </summary>
		/// <param name="obj">The object</param>
		/// <param name="muted">If true, the color is pulled toward the background color</param>
		/// <param name="backColor">The background color, for muting. If not given, the background
		///   color is white</param>
		/// <returns>The color of the object</returns>
		public Color GetColor(object obj, bool muted = false, Color? backColor = null)
		{
			var back = backColor ?? Color.White;

			if (muted)
				return Average(GetColor(obj, false, backColor), back);

			if (_colors.TryGetValue(obj, out var existingColor))
				return existingColor;

			Color newColor = Color.Black;
			if (_colors.Count >= MaxColors)
				newColor = _colors.Values.RandomElement(_rand);
			else
			{
				int bestDist = 0;

				// Create 100 random colors, choose the one most distant from all existing colors
				for (int i = 0; i < 100; ++i)
				{
					Color color = Color.FromArgb(_rand.Next(256), _rand.Next(256), _rand.Next(256));
					var existingColors = _colors.Select(x => x.Value).Concat(new Color[] { back });
					int dist = existingColors.Min(c =>
					{
						int rd = c.R - color.R;
						int gd = c.G - color.G;
						int bd = c.B - color.B;
						return 4 * rd * rd + 9 * gd * gd + bd * bd;
					});

					if (dist > bestDist)
					{
						bestDist = dist;
						newColor = color;
					}
				}
			}

			_colors.Add(obj, newColor);

			return newColor;
		}

		/// <summary>
		/// Returns the color that is half way between the given colors
		/// </summary>
		/// <returns></returns>
		public static Color Average(Color color1, Color color2)
		{
			return Color.FromArgb((color1.R + color2.R) / 2, (color1.G + color2.G) / 2, (color1.B + color2.B) / 2);
		}
	}
}
